# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo:4.4.17-rc0
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
    volumes:
      - mongo-data:/data/db
      - ./data:/opt/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - airflow-etl-ggmaps_ggmaps
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: mongodb-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: "FALSE"
    networks:
      - airflow-etl-ggmaps_ggmaps

networks:
  airflow-etl-ggmaps_ggmaps:
    external: true
volumes:
  mongo-data: